services:
  frontend:
    container_name: opa-finance-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: '/api'
    ports:
      - '8081:80'
    restart: unless-stopped
    networks:
      - opa-finance-net

networks:
  opa-finance-net:
    external: true
