services:
  frontend:
    container_name: opa-finance-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: '/api'
    restart: unless-stopped
    networks:
      - proxy-net
      - opa-finance-net

networks:
  proxy-net:
    external: true
  opa-finance-net:
    external: true
